name: tests
on:
  push:
    branches:
      - develop

jobs:
  tasts-start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: yarn install
      - run: yarn prepare
      - run: yarn jest
